upstream change_api {
least_conn;
server 10.54.29.208:1126 weight=1 max_fails=2 fail_timeout=30s;
server 10.54.29.207:1126 weight=1 max_fails=2 fail_timeout=30s;
#server 10.54.29.209:1126 weight=1 max_fails=2 fail_timeout=30s;
#server 10.54.29.210:1126 weight=1 max_fails=3 fail_timeout=30s;
#server 10.54.29.210:5001 weight=1 max_fails=2 fail_timeout=30s;
keepalive 10;
}



upstream change_api_two{
least_conn;
server 10.78.9.45:2222 weight=1 max_fails=2 fail_timeout=30s;
#server 10.54.29.210:5001 weight=1 max_fails=2 fail_timeout=30s;
keepalive 10;
}



# 新增 upstream（专门处理 model=0 的请求）
upstream change_api_two_model0 {
    least_conn;
    server 10.136.234.255:8116 weight=1 max_fails=2 fail_timeout=30s;
    keepalive 10;
}




log_format  change_log  '客户端:$remote_addr 请求耗时:$request_time 转发到:$upstream_addr  时间: [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';



server{
listen 11126;
server_name change_api;
access_log /data0/jiangtao16/nginx/log/change_api.log change_log;
location / {
 proxy_buffers 3 100m;
 proxy_connect_timeout 180s;
 proxy_read_timeout 180s;
 client_max_body_size 50m;
 proxy_buffer_size 50m;
 proxy_pass http://change_api;
 proxy_set_header Connection "";
 proxy_buffering off;
}
}






server{
listen 11127;
server_name change_api_two;
access_log /data0/jiangtao16/nginx/log/change_api.log change_log;



 # 优先级1：URL 包含 /split_video → 强制转发到 10.78.9.45:2222（即 change_api_two）

location ~* /split_video {
    # 额外判断参数中是否存在 type=split（不区分大小写）
    # 路径含 /split_video 时直接转发
    proxy_buffers 3 100m;
    proxy_connect_timeout 180s;
    proxy_read_timeout 180s;
    client_max_body_size 50m;
    proxy_buffer_size 50m;
    proxy_pass http://change_api_two;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_buffering off;
}



location / {
 proxy_buffers 3 100m;
 proxy_connect_timeout 180s;
 proxy_read_timeout 180s;
 client_max_body_size 50m;
 proxy_buffer_size 50m;
#if  ($args ~* "(^|&)type=split($|&)" || $args ~* "(^|&)mode=1($|&)") {
#            proxy_pass http://change_api_two;
#            #return 400; # 防止后续逻辑执行（nginx 要求 if 内 proxy_pass 后需终止）
#        }





 if ($args ~* "(^|&)mode=1") {
 proxy_pass http://change_api_two;
  }

 if ($args ~* "(^|&|\?)type=split") {
 proxy_pass http://change_api_two;
  }



  proxy_pass http://change_api_two_model0;  # 带 model=0 → 转发到 10.136.234.255:8116
 #proxy_pass http://change_api_two;
 proxy_set_header Connection "";
 proxy_buffering off;
}
}




