#ip1.push.weibo.cn:14546
upstream cat_star_api {
least_conn;
server 10.78.9.45:14546 weight=1 max_fails=2 fail_timeout=30s;
# server 10.54.29.207:1126 weight=1 max_fails=2 fail_timeout=30s;
#server 10.54.29.209:1126 weight=1 max_fails=2 fail_timeout=30s;
#server 10.54.29.210:1126 weight=1 max_fails=3 fail_timeout=30s;
#server 10.54.29.210:5001 weight=1 max_fails=2 fail_timeout=30s;
keepalive 10;
}

log_format  cat_star_log  '客户端:$remote_addr 请求耗时:$request_time 转发到:$upstream_addr  时间: [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';


server{
listen 14546;
server_name cat_star_api;
access_log /data0/jiangtao16/nginx/log/cat_star_api.log cat_star_log;
location / {
 proxy_buffers 3 100m;
 proxy_connect_timeout 180s;
 proxy_read_timeout 180s;
 client_max_body_size 50m;
 proxy_buffer_size 50m;
 proxy_pass http://cat_star_api;
 proxy_set_header Connection "";
 proxy_buffering off;
}
}


# server {
#     listen 11127;

#     # 特殊通道：处理视频切分
#     location ~* /split_video { 
#         proxy_pass http://change_api_two; # 去 45 机器
#     }

#     # 默认通道：处理其他所有杂活
#     location / {
#         # 里面虽然也有 if 判断，但它是默认的大桶
#         proxy_pass http://change_api_two_model0; # 去 255 机器
#     }
# }