[program:camera_server]
; 动态路径修改：
command=/bin/bash -c "export PYTHONPATH=$PYTHONPATH:%(ENV_PROJ_ROOT)s && %(ENV_CONDA_ROOT)s/bin/python %(ENV_PROJ_ROOT)s/agi_server/camera_classify/camera_main_server.py"

; 运行目录
directory=%(ENV_PROJ_ROOT)s

user=root
stopasgroup=true
autorestart=true
redirect_stderr=true

; 日志路径 (保留了原本的 sup 子目录)
stdout_logfile=%(ENV_PROJ_ROOT)s/log/sup_log/camera_supervisor.log
loglevel=warn