[program:gpu_server]
command=/bin/bash run_keep_alive.sh
directory=/workspace/work/zhipeng16/git/yolo8-plus-iopaint/agi_server/gpu_server
user=root
stopasgroup=true ; 确保 stop 时能把那 3 个后台进程一起杀掉
killasgroup=true
autorestart=true
redirect_stderr=true
stdout_logfile=/workspace/work/zhipeng16/git/yolo8-plus-iopaint/log/sup_log/gpu_1.log