[program:llm_server]
command=/bin/bash start_server.sh
directory=/workspace/work/zhipeng16/git/yolo8-plus-iopaint/agi_server/llm_server
user=root
stopasgroup=true
killasgroup=true
autorestart=true
redirect_stderr=true
stdout_logfile=/workspace/work/zhipeng16/git/yolo8-plus-iopaint/log/sup_log/llm_server.log
