[program:cv_server]
; 核心修改：
; 1. %(ENV_CONDA_ROOT)s -> 自动指向 Conda 环境的 bin/python
; 2. %(ENV_PROJ_ROOT)s  -> 自动指向项目代码
command=/bin/bash -c "export PYTHONPATH=$PYTHONPATH:%(ENV_PROJ_ROOT)s && %(ENV_CONDA_ROOT)s/bin/python %(ENV_PROJ_ROOT)s/agi_server/cv_server.py"

; 运行目录也改成动态的
directory=%(ENV_PROJ_ROOT)s

user=root
stopasgroup=true
autorestart=true
redirect_stderr=true

; 日志也放到项目目录下
stdout_logfile=%(ENV_PROJ_ROOT)s/log/sup_log/sup_mask.log
loglevel=warn