[program:question_server]
; 动态路径修改：
command=/bin/bash -c "export PYTHONPATH=$PYTHONPATH:%(ENV_PROJ_ROOT)s && %(ENV_CONDA_ROOT)s/bin/python %(ENV_PROJ_ROOT)s/agi_server/main_app/question_video_api_server.py"

; 运行目录
directory=%(ENV_PROJ_ROOT)s

user=root
stopasgroup=true
autorestart=true
redirect_stderr=true

; 日志路径
stdout_logfile=%(ENV_PROJ_ROOT)s/log/sup_log/sup_question.log
loglevel=warn